/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Principal = IDL.Principal;
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'author' : Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Rule = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Time,
});
export const OwnerProfile = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
});
export const PlayerCount = IDL.Record({
  'max' : IDL.Nat,
  'updatedAt' : Time,
  'current' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRule' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteRule' : IDL.Func([IDL.Nat], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllRules' : IDL.Func([], [IDL.Vec(Rule)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOwnerProfile' : IDL.Func([], [IDL.Opt(OwnerProfile)], ['query']),
  'getPlayerCount' : IDL.Func([], [PlayerCount], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateOwnerProfile' : IDL.Func([OwnerProfile], [], []),
  'updatePlayerCount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateRule' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'author' : Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Rule = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Time,
  });
  const OwnerProfile = IDL.Record({ 'contact' : IDL.Text, 'name' : IDL.Text });
  const PlayerCount = IDL.Record({
    'max' : IDL.Nat,
    'updatedAt' : Time,
    'current' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRule' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteRule' : IDL.Func([IDL.Nat], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllRules' : IDL.Func([], [IDL.Vec(Rule)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOwnerProfile' : IDL.Func([], [IDL.Opt(OwnerProfile)], ['query']),
    'getPlayerCount' : IDL.Func([], [PlayerCount], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateOwnerProfile' : IDL.Func([OwnerProfile], [], []),
    'updatePlayerCount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateRule' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };