/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'author' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface OwnerProfile { 'contact' : string, 'name' : string }
export interface PlayerCount {
  'max' : bigint,
  'updatedAt' : Time,
  'current' : bigint,
}
export type Principal = Principal;
export interface Rule { 'id' : bigint, 'content' : string, 'createdAt' : Time }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRule' : ActorMethod<[string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string, string], undefined>,
  'deleteRule' : ActorMethod<[bigint], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllRules' : ActorMethod<[], Array<Rule>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOwnerProfile' : ActorMethod<[], [] | [OwnerProfile]>,
  'getPlayerCount' : ActorMethod<[], PlayerCount>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateOwnerProfile' : ActorMethod<[OwnerProfile], undefined>,
  'updatePlayerCount' : ActorMethod<[bigint, bigint], undefined>,
  'updateRule' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];